const Categories = [
    { category: "General Knowledge", value: 9, img: "gk.png" },
    { category: "Books", value: 10, img: "books.png" },
    { category: "Films", value: 11, img: "films.png" },
    { category: "Music", value: 12, img: "music.png" },
    { category: "Musicals and Theaters", value: 13, img: "theatre.png" },
    { category: "Television", value: 14, img: "television.png" },
    { category: "Video Games", value: 15, img: "videogames.png" },
    { category: "Board Games", value: 16, img: "boardgames.png" },
    { category: "Science and Nature", value: 17, img: "science.png" },
    { category: "Computer", value: 18, img: "computer.png" },
    { category: "Mathematics", value: 19, img: "math.png" },
    { category: "Mythology", value: 20, img: "mytho.png" },
    { category: "Sports", value: 21, img: "sports.png" },
    { category: "Geography", value: 22, img: "geography.png" },
    { category: "History", value: 23, img: "history.png" },
    { category: "Politics", value: 24, img: "politics.png" },
    // { category: "Art", value: 25 },
    { category: "Celebrities", value: 26, img: "celebrities.png" },
    { category: "Animals", value: 27, img: "animals.png" },
    { category: "Vehicles", value: 28, img: "vehicles.png" },
    { category: "Comics", value: 29, img: "comics.png" },
    { category: "Gadgets", value: 30, img: "gadgets.png" },
    { category: "Japanese Anime", value: 31, img: "anime.png" },
    { category: "Cartoon and Animations", value: 32, img: "cartoons.png" },
];

export default Categories;